import Head from "next/head";
import Card from "../src/components/Card";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Solidity101</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3 className="text-center bg-gradient-to-tr from-purple-400 to-purple-800 bold text-4xl mt-2">solidity101-LFG</h3>
      </main>

      <Card name="WAGMI" />

    </div>
  );
}
