import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Solidity101</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3 className="text-center bold text-4xl mt-2">solidity101</h3>
      </main>
    </div>
  );
}



